### PR TITLE
Codebase formatting with ``f-string``

### PR DESCRIPTION
**Pull request by ThibFrgsGmz**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---

## Change Description

- Replace calls to ``string.format()`` with ``f-strings`` [ref](https://docs.sourcery.ai/refactorings/use-fstring-for-formatting/)
- Replace the use of the ``%`` string interpolation operator with ``f-strings`` (only ``%s`` operator) [ref](https://docs.sourcery.ai/refactorings/replace-interpolation-with-fstring/)

## Rationale

According to the [Python documentation](https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting), using the ``%`` operator to format strings can lead to "a variety of quirks that lead to a number of common errors."

[PEP 498](https://peps.python.org/pep-0498/) added F-strings to Python in version 3.6. F-strings are a versatile and powerful method of string formatting. Because the code looks more like the output, they make it shorter and more readable.

## Future Work

Deals with operators other than ``%s`` like ``%d``.

### CODE REVIEW

**Comment by ThibFrgsGmz** [comment]
@LeStarch Damn, I was testing my fork with linters. As I broke a lot of things on my fork,
I wanted to start from a healthy base and delete it and the fork...
I don't know if it's possible to recover the commit.

**Comment by LeStarch** [comment]
The commit is still out there.  Recovering it is the issue.

**Comment by LeStarch** [comment]
Look here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

If you checkout the merged pull-request branch, it should exist.  Then you can make that a new branch.

Or if you prefer, follow those instructions to fetch the PR. Then from a clean codebase:

```
git checkout -b somebranch <upstream>/devel
git cherry-pick 9724f6e95cd32890e478b72283cf0e6850af4ccb
```
This will migrate over exactly the above commit into  a new off-devel branch

**Comment by LeStarch** [comment]
I am not sure this will work, but I think it will.  You should do these steps soon as eventually the repository will be garbage-collected and it will disappear.

**Comment by ThibFrgsGmz** [comment]
Ok great thanks! I was able to retrieve the commits from my PR #51 #52 #53.
I will now see how to repatriate them in my fork and submit them via other PRs.

**Comment by ThibFrgsGmz** [comment]
@LeStarch Since you were able to reopen it, do you have the option to merge it? In that case, I don't need to redo the PR and let you look at my different PRs, right ?

**Comment by LeStarch** [comment]
I can, but it looks like CI still needs some fixes.

**Comment by ThibFrgsGmz** [comment]
@LeStarch Ok, there seems to be a problem on Black and then it seems to be related to the FPP installation.
Do you want me to look into fixing the CI or do you want to wait until you finish the new FPrime install procedure via pip to fix it?

**Comment by LeStarch** [comment]
I have a fix for the Black/CI install issue.

**Review by LeStarch — APPROVED** [review]

**Comment by LeStarch** [comment]
Only format not working.  I am going to merge and push a reformat as a separate PR.  This is to not lose the changes.

**Comment by ThibFrgsGmz** [comment]
@LeStarch Okay, nice what about my other PRs that suffered the same closing fate? Can you reopen them?

**Comment by LeStarch** [comment]
Sorry, I did not realize there were more.

**Pull request merged**
