### PR TITLE
Improve dictionary updating

### PR DESCRIPTION
**Pull request by ThibFrgsGmz**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---

## Change Description

This PR includes the following changes:
- Added a single value to the dictionary directly rather than using update() [ref](https://docs.sourcery.ai/refactorings/simplify-dictionary-update/).
- Changed dictionary assignments and updates to use the union operator [ref](https://docs.sourcery.ai/refactorings/dict-assign-update-to-union/).

## Rationale

Adding an entry directly to a dictionary is easier than using the update() method. It also eliminates the overhead of creating a new dictionary and calling a method, which should improve performance a bit.

Look out for the union operator for dictionaries, it was added in **Python 3.9** ([PEP 584](https://peps.python.org/pep-0584/)) and provides a concise way to merge dictionaries without using the copy/update statements.

## Testing/Review Recommendations

(void)

## Future Work

(void)

### CODE REVIEW

**Comment by LeStarch** [comment]
Our code needs to support active-life python versions.  Thus the `|=` operator in this PR will need to be reverted as it is only supported as near as I can tell in Python 3.9+.

**Comment by LeStarch** [comment]
I look here to see the versions that are still active: https://endoflife.date/python

**Comment by ThibFrgsGmz** [comment]
@LeStarch Um, I don't know how to do that, especially since I deleted my original fork... I think it would be better to close this PR, no?

**Comment by LeStarch** [comment]
Yeah....looks like it.

**Comment by ThibFrgsGmz** [comment]
@LeStarch New PR without the ``|=`` is https://github.com/fprime-community/fprime-tools/pull/69

**Pull request closed without merging**
